### ISSUE TITLE
什么时候可以把支持升级到python3.7啊

### ISSUE THREAD

**Issue by 52lemon** [alvan/luokr.com#14]
现在都使用python3.7了，什么时候升级下

**Comment by laalaguer** [comment]
两年没人回issue了。估计放弃了吧。

看重Tornado框架的都该转Go了。

**Comment by 52lemon** [comment]
> 两年没人回issue了。估计放弃了吧。
> 
> 看重Tornado框架的都该转Go了。

公司后端从flask转tornado，都不转go，没办法，学习一下，这个项目现在跑起来各种问题，想从sqlite切换到mysql有更多地方要改，这个issue提了好久，也不见开发大佬回复啊
