### ISSUE TITLE
Where is etc.py?

### ISSUE THREAD

**Issue by javadba** [alvan/luokr.com#15]
The README.md shows app/etc.py .  Also the app/tools/dbase.py and other files have:

   from app.etc import etc

But that file is not present. So is this project self inconsistent with the documentation and its own scripts?  Please advise: i do like the image of your pages.

**Comment by alvan** [comment]
@javadba 
There are some tools under dir "app/tools".
You can run the `envir.py` to init the sample etc.py file.

Please also check the README file for more details.
Thanks.
