### ISSUE TITLE
能不能写个简单的环境部署步骤

### ISSUE THREAD

**Issue by dainixiao** [alvan/luokr.com#7]
我是一个python小白，部署了python环境，但是访问静态资源的时候访问不到（js文件404,handler.asset 这里面的东西访问不到，没有部署nginx环境），不知道还需要什么步骤？希望得到指点指点，还要为啥不用mongodb?

**Comment by alvan** [comment]
@dainixiao 
Nginx配置请参考：https://github.com/alvan/luokr.com/blob/master/doc/luokr.com.nginx.conf

使用MongoDB或者Sqlite，只是我的个人喜好……

**Comment by dainixiao** [comment]
我配置了nginx环境：
   #new 
    upstream tornado {
            server 127.0.0.1:8001;
            server 127.0.0.1:8002;
            server 127.0.0.1:8003;
            server 127.0.0.1:8004;
    }

    include       mime.types;
    default_type  application/octet-stream;
   
    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;
    #new 
    access_log /var/log/nginx/access.log;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;
    #new
    proxy_read_timeout 200;

    #gzip  on;

    server {
        server_name www.luokr.com;
        return 301 $scheme://luokr.com$request_uri;
    }

    server {
        listen       8088;
        server_name  luokr.com;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        #root /Users/liu/Desktop/luokr.com/www;
        #index index.html;
        try_files $uri @tornado;

        # 静态文件直接由Nginx处理
        #location /static/{
        #alias /Users/liu/Desktop/luokr.com/www;
        #expires 24h;
        #}
        location /static/ {
            root /Users/liu/Desktop/luokr.com/www;
            if ($query_string) {
                expires max;
            }
        }
        
        location @tornado{
        proxy_pass_header Server;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        # 把请求方向代理传给tornado服务器，负载均衡
        proxy_pass http://tornado;
        }

但是还是访问不到www目录底下的静态资源文件.

**Comment by dainixiao** [comment]
现在可以了，我重启了一下tornado端口了，可以访问到静态资源了.
