### ISSUE TITLE
提个小小的优化建议,项目定义为python类型

### ISSUE THREAD

**Issue by dainixiao** [alvan/luokr.com#8]
有没有发现在搜索luokr.com这个项目的时候，项目的类型被定义为了javascript，这样不利于搜索python项目的时候被发现，建议定义为python类型（当然，查阅了一些资料显示这个类型是github根据代码量来定义类型的），我是一个python小白（我主要是开发Andorid的），接触这个项目大概有一个月之久了，感觉写的挺不错的，真的挺感谢有这个一个开源项目的，算是从这个项目入门python的吧~（好项目就应该让更多的人知道嘛，当时在github中搜索python tornado 这样组合的项目真的是少之又少，还是从你的官网的中找到的github地址），3q

**Comment by alvan** [comment]
@dainixiao 
这个据我所知是github代码分析自动归类的，应该不能自定义。
