### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by dainixiao** [alvan/luokr.com#9]
tornado 怎么生成带html后缀的页面（伪静态页面）

**Comment by alvan** [comment]
@dainixiao 
RequestHandler的render方法即可，渲染后的结果在response中，可以自行获取保存为磁盘文件。
URL可以自定义，带不带html都可以。

**Comment by dainixiao** [comment]
有这方面的例子推荐吗？不太会写这样的demo

**Comment by dainixiao** [comment]
![Uploading image.png…]()
是先调用render_string  这个方法返回回来网页的html整个结构再去做保存？然后请求的URL直接指向这个本地的html文件？

**Comment by dainixiao** [comment]
def render(self, template_name, **kwargs):
        """Renders the template with the given arguments as the response."""
        if self._finished:
            raise RuntimeError("Cannot render() after finish()")

（****** html = self.render_string(template_name, **kwargs)****）

**Comment by alvan** [comment]
@dainixiao 
你可以在nginx配置使用IF语句检查html文件是否存在，不存在则将请求转发给Python处理，生成并保存html再返回即可。
